---
- name: "OS fingerprinting "
  debug:
    msg:
    - " ansible_os_family: {{ hostvars[inventory_hostname].ansible_os_family }} "
    - " ansible_distribution: {{ hostvars[inventory_hostname].ansible_distribution }}"
    - " ansible_distribution_major_version: {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
    - " ansible_distribution_release: {{ hostvars[inventory_hostname].ansible_distribution_release }}"
    - " ansible_distribution_version: {{ hostvars[inventory_hostname].ansible_distribution_version }}"

- name: "Add Ubuntu nginx"
  include_tasks: nginx_debian.yml
  when: " ansible_os_family == 'Debian' and ansible_distribution in ['Ubuntu'] and ansible_distribution_version in ['19.04'] "

- name: "Add RedHat nginx"
  include_tasks: nginx_redhat.yml
  when: " ansible_os_family == 'RedHat' and ansible_distribution in ['CentOS'] and ansible_distribution_version in ['8.0'] "
