---
# [WARNING]: Could not find aptitude. Using apt-get instead fix
- name: "APT: Install aptitude package"
  apt:
   name: aptitude
   force_apt_get: yes
- name: "Install nginx"
  package:
    name: "{{ item }}"
    state: latest
  with_items:
      - "nginx"
- name: "Enable and start nginx service"
  service: name=nginx state=started enabled=yes
